version:  '3.8'

services:
  web:
    build: ./algotrade
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./algotrade/:/usr/src/algotrade/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: