# Generated by Django 5.1.1 on 2024-10-05 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=255)),
                ('constant_name', models.CharField(max_length=255, unique=True)),
                ('stock_table', models.CharField(blank=True, max_length=255, unique=True)),
                ('option_table', models.CharField(blank=True, max_length=255, unique=True)),
                ('token_id', models.IntegerField()),
                ('time_frame', models.CharField(default='1d', max_length=255)),
                ('is_stock_active', models.BooleanField(default=False)),
                ('is_option_active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('master_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backdata.mastertable')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
